CREATE TABLE thoughts (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    thought TEXT NOT NULL,
    views INT NOT NULL DEFAULT 0,
    likes INT NOT NULL DEFAULT 0,
    dislikes INT NOT NULL DEFAULT 0,
    created TIMESTAMPTZ NOT NULL DEFAULT NOW()
);