root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ."
  bin = "tmp/main"
  exclude_dir = ["vendor", "tmp"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  delay = 1000 # ms

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"